name: Hourly Nifty Scan

on:
  schedule:
    # every 5 minutes (GitHub minimum)
    - cron: "*/5 * * * *"
  workflow_dispatch: {}  # manual trigger from Actions tab

jobs:
  run-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scan and save CSV
        run: |
          python -c "from scan_helpers import run_scan_and_save_csv; run_scan_and_save_csv()"
